scss_files: '**/*.scss'

severity: warning

linters:
    Indentation:
        enabled: true
        allow_non_nested_indentation: false
        character: space
        width: 4

    SelectorFormat:
        enabled: false

    LeadingZero:
        enabled: true
        style: include_zero
